# Generated by Django 5.2.1 on 2025-05-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_event_capacity'),
        ('app', '0018_notification_users'),
    ]

    operations = [
    ]
