# Generated by Django 5.2 on 2025-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_0017_event_capacity_0018_notification_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado'), ('Agotado', 'Agotado'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20),
        ),
    ]
