# Generated by Django 5.2 on 2025-05-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_event_status'),
        ('app', '0020_favorite'),
    ]

    operations = [
    ]
