# Generated by Django 5.2 on 2025-05-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_0020_event_status_0020_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.IntegerField(choices=[(1, 'Muy insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy satisfecho')])),
                ('ease_of_search', models.IntegerField(choices=[(1, 'Muy difícil'), (2, 'Difícil'), (3, 'Neutral'), (4, 'Fácil'), (5, 'Muy fácil')])),
                ('payment_experience', models.IntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Aceptable'), (4, 'Bueno'), (5, 'Excelente')])),
                ('received_ticket', models.BooleanField()),
                ('would_recommend', models.IntegerField(choices=[(1, 'Definitivamente no'), (2, 'Probablemente no'), (3, 'No estoy seguro/a'), (4, 'Probablemente sí'), (5, 'Definitivamente sí')])),
                ('additional_comments', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
        ),
    ]
