# Generated by Django 5.2 on 2025-05-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_satisfactionsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Porcentaje de descuento aplicado (0-100)', null=True),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='app.event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.discountcode'),
        ),
    ]
